PATCH http://localhost:3000/foo

### Login User
POST http://localhost:3000/signin
Content-Type: application/json

{
  "email": "email17@email.ru",
  "password": "13"
}


### Create User
POST http://localhost:3000/signup
Content-Type: application/json

{
  "name": "Новый пользователь 18",
  "about": "Информация о себе",
  "avatar": "https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
  "email": "email18",
  "password": "123"
}


### Get Users
GET  http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmM1YzY4YmU0MGQ3NTgyYzExMzRhNWIiLCJpYXQiOjE2NTcxMzI0OTgsImV4cCI6MTY1NzczNzI5OH0.zQ97gkm4FYu81l2aX2crOUcNbvceyWEuUELWr-2z6PA


### Get User By ID
GET  http://localhost:3000/users/62c577b7641f6b37202adc7b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmM1YzY4YmU0MGQ3NTgyYzExMzRhNWIiLCJpYXQiOjE2NTcxMzI0OTgsImV4cCI6MTY1NzczNzI5OH0.zQ97gkm4FYu81l2aX2crOUcNbvceyWEuUELWr-2z6PA


### Get Current User Info
GET http://localhost:3000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmM1YzY4YmU0MGQ3NTgyYzExMzRhNWIiLCJpYXQiOjE2NTcxMzI0OTgsImV4cCI6MTY1NzczNzI5OH0.zQ97gkm4FYu81l2aX2crOUcNbvceyWEuUELWr-2z6PA


### Update User Profile
PATCH http://localhost:3000/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmM1YzY4YmU0MGQ3NTgyYzExMzRhNWIiLCJpYXQiOjE2NTcxMzI0OTgsImV4cCI6MTY1NzczNzI5OH0.zQ97gkm4FYu81l2aX2crOUcNbvceyWEuUELWr-2z6PA

{
  "name": "Имя пользователя 17",
  "about": "Н"
}


### Update User Avatar
PATCH http://localhost:3000/users/me/avatar
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmM1YzY4YmU0MGQ3NTgyYzExMzRhNWIiLCJpYXQiOjE2NTcxMzI0OTgsImV4cCI6MTY1NzczNzI5OH0.zQ97gkm4FYu81l2aX2crOUcNbvceyWEuUELWr-2z6PA

{
  "avatar": "2"
}


### Get Cards
GET  http://localhost:3000/cards
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmM1YzY4YmU0MGQ3NTgyYzExMzRhNWIiLCJpYXQiOjE2NTcxMzI0OTgsImV4cCI6MTY1NzczNzI5OH0.zQ97gkm4FYu81l2aX2crOUcNbvceyWEuUELWr-2z6PA


### Create New Card
POST http://localhost:3000/cards
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmM1YzY4YmU0MGQ3NTgyYzExMzRhNWIiLCJpYXQiOjE2NTcxMzI0OTgsImV4cCI6MTY1NzczNzI5OH0.zQ97gkm4FYu81l2aX2crOUcNbvceyWEuUELWr-2z6PA

{
  "name": "1",
  "link": "https://sib.fm/storage/article/March2021/IDsV2DD5Qhwj5kWTpfYG.jpeg"
}


### Like Card
PUT http://localhost:3000/cards/92c5cd83110a7d4673162b30/likes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmM1YzY4YmU0MGQ3NTgyYzExMzRhNWIiLCJpYXQiOjE2NTcxMzI0OTgsImV4cCI6MTY1NzczNzI5OH0.zQ97gkm4FYu81l2aX2crOUcNbvceyWEuUELWr-2z6PA



### Dislike Card
DELETE http://localhost:3000/cards/62ac66743e0cf17bc5e49512/likes


### Delete Card By ID
DELETE http://localhost:3000/cards/62c0a02af5b286a506f87af6
