PATCH http://localhost:3000/foo

### Login User
POST http://localhost:3000/signin
Content-Type: application/json

{
  "email": "email33@email.com",
  "password": "123"
}


### Create User
POST http://localhost:3000/signup
Content-Type: application/json

{
  "email": "email33@email.com",
  "password": "123"
}


### Get Users
GET  http://localhost:3000/users


### Get User By ID
GET  http://localhost:3000/users/2c0a02af5b286a506f87af6


### Get Current User Info
GET http://localhost:3000/users/me


### Update User Profile
PATCH http://localhost:3000/users/me
Content-Type: application/json

{
  "name": "Новое имя пользователя 33",
  "about": "Новое инфо"
}


### Update User Avatar
PATCH http://localhost:3000/users/me/avatar
Content-Type: application/json

{
  "avatar": "http://ya.ru"
}


### Get Cards
GET  http://localhost:3000/cards


### Create New Card
POST http://localhost:3000/cards
Content-Type: application/json

{
  "name": "Котик Мяу 4",
  "link": "http://ya.ru"
}


### Like Card
PUT http://localhost:3000/cards/2c7f9e4674351359054c4bd/likes


### Dislike Card
DELETE http://localhost:3000/cards/2c7f9e4674351359054c4bd/likes


### Delete Card By ID
DELETE http://localhost:3000/cards/6c5cd83110a7d4673162b30
